# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: backend # Use an image built from the specified dockerfile in the `spring-boot-oauth2-social-login` directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - back
      - front

  # Frontend Service
  app-client:
    build:
      context: frontend # Use an image built from the specified dockerfile in the `angular-11-social-login` directory.
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://127.0.0.1:8080/
    ports:
      - "8081:80" # Mapeamos el puerto expuesto en el contenedor al puerto 8081 en la máquina anfi
    restart: always
    depends_on:
      - app-server
    networks:
      - front

# Networks to be created to facilitate communication between containers
networks:
  back:
  front: